# Generated by Django 5.2.4 on 2025-07-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SDQResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q2', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q3', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q4', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q5', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q6', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q7', models.IntegerField(choices=[(2, 'Not True'), (1, 'Somewhat True'), (0, 'Certainly True')])),
                ('q8', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q9', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q10', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q11', models.IntegerField(choices=[(2, 'Not True'), (1, 'Somewhat True'), (0, 'Certainly True')])),
                ('q12', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q13', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q14', models.IntegerField(choices=[(2, 'Not True'), (1, 'Somewhat True'), (0, 'Certainly True')])),
                ('q15', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q16', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q17', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q18', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q19', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q20', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q21', models.IntegerField(choices=[(2, 'Not True'), (1, 'Somewhat True'), (0, 'Certainly True')])),
                ('q22', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q23', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q24', models.IntegerField(choices=[(0, 'Not True'), (1, 'Somewhat True'), (2, 'Certainly True')])),
                ('q25', models.IntegerField(choices=[(2, 'Not True'), (1, 'Somewhat True'), (0, 'Certainly True')])),
            ],
        ),
    ]
