from django.contrib.auth.models import User
from django.test import TestCase
from django.urls import reverse

from .models import Post


class PostViewTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.author = User.objects.create_user("author", password="pass-12345")
        cls.posts = [
            Post.objects.create(title=f"Post {i}", body="Body text", author=cls.author)
            for i in range(4)
        ]
        cls.posts[0].tags.add("trauma")

    def test_list_is_public(self):
        response = self.client.get(reverse("posts:list"))
        self.assertEqual(response.status_code, 200)

    def test_detail_by_slug(self):
        response = self.client.get(reverse("posts:page", args=[self.posts[0].slug]))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Post 0")

    def test_tag_filter(self):
        response = self.client.get(reverse("posts:post_list_by_tag", args=["trauma"]))
        self.assertEqual(response.status_code, 200)

    def test_out_of_range_page_returns_last_page(self):
        # 4 posts at 3 per page = 2 pages; page 999 must clamp to the last page
        response = self.client.get(reverse("posts:list"), {"page": 999})
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context["posts"].number, 2)

    def test_non_integer_page_returns_first_page(self):
        response = self.client.get(reverse("posts:list"), {"page": "abc"})
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context["posts"].number, 1)

    def test_slug_autogenerated_on_save(self):
        post = Post.objects.create(title="A Brand New Post", body="x", author=self.author)
        self.assertEqual(post.slug, "a-brand-new-post")
