from django.contrib.auth.models import User
from django.test import TestCase
from django.urls import reverse

from .models import Topic


class ResourceViewTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.author = User.objects.create_user("author", password="pass-12345")
        cls.topics = [
            Topic.objects.create(title=f"Resource {i}", body="Body text", author=cls.author)
            for i in range(11)
        ]
        cls.topics[0].tags.add("attachment")

    def test_list_is_public(self):
        response = self.client.get(reverse("resources:resource_list"))
        self.assertEqual(response.status_code, 200)

    def test_detail_by_slug(self):
        response = self.client.get(reverse("resources:page", args=[self.topics[0].slug]))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Resource 0")

    def test_tag_filter(self):
        response = self.client.get(
            reverse("resources:resource_list_by_tag", args=["attachment"])
        )
        self.assertEqual(response.status_code, 200)

    def test_out_of_range_page_returns_last_page(self):
        # 11 topics at 10 per page = 2 pages; page 999 must clamp to the last page
        response = self.client.get(reverse("resources:resource_list"), {"page": 999})
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context["resources"].number, 2)

    def test_slug_autogenerated_on_save(self):
        topic = Topic.objects.create(title="A Brand New Resource", body="x", author=self.author)
        self.assertEqual(topic.slug, "a-brand-new-resource")
