# Generated by Django 5.2 on 2025-06-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashcard_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('how_to_do_it', models.TextField()),
                ('what_you_need', models.TextField()),
                ('context', models.TextField()),
                ('sort_order', models.IntegerField()),
            ],
        ),
    ]
