# Generated by Django 5.2 on 2025-06-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_chatturn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='context',
            new_name='who_where_when_why',
        ),
    ]
