# Generated by Django 5.2 on 2025-06-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_rename_context_flashcard_who_where_when_why'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='flashcard_id',
            field=models.IntegerField(unique=True),
        ),
    ]
