# Generated by Django 5.2 on 2025-07-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_alter_flashcard_options_alter_flashcard_flashcard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcard_images/'),
        ),
    ]
