# Generated by Django 5.2.4 on 2026-02-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_scenarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scenarios',
            new_name='Scenario',
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ['sort_order'], 'verbose_name': 'Scenario', 'verbose_name_plural': 'Scenarios'},
        ),
    ]
