# Generated by Django 5.2.4 on 2026-06-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_rename_scenarios_scenario_alter_scenario_options'),
        # Data must be copied into core_chatturn before this table is dropped
        ('core', '0002_copy_chat_turns'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatTurn',
        ),
    ]
