# Generated by Django 5.2.4 on 2026-07-05 19:23

import myproject.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_delete_chatturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcard_images/', validators=[myproject.core.validators.validate_upload_size]),
        ),
    ]
