# Generated by Django 5.2.4 on 2026-06-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolerance', '0003_remove_checkin_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='intensity',
        ),
        migrations.AddField(
            model_name='weeklymap',
            name='visible_slots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
