# Generated by Django 5.2.4 on 2026-06-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolerance', '0004_add_visible_slots_remove_intensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='abc_after',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='abc_before',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='abc_during',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='incident_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='observation',
            name='people_present',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='observation',
            name='place',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
