# Generated by Django 5.2.4 on 2025-11-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='body',
            new_name='text',
        ),
    ]
