# Generated by Django 5.2 on 2025-06-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='banner',
            new_name='image',
        ),
    ]
