name: Deploy Django to Azure Web App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🚀 Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: vs-training-website
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

      - name: 🛠️ Migrate & collectstatic
        if: always()
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp ssh \
              --name vs-training-website \
              --resource-group appsvc_linux_northeurope_basic \
              --command '
                set -e

                cd /home/site/wwwroot

                # If Oryx left a package, extract it so manage.py and apps exist here
                if [ -f output.tar.gz ]; then
                  echo "Extracting output.tar.gz into wwwroot..."
                  tar -xzf output.tar.gz -C /home/site/wwwroot
                fi

                # Figure out the correct settings module automatically
                if [ -d "myprojectsettings" ]; then
                  SETTINGS="myprojectsettings.settings"
                elif [ -d "myproject/myprojectsettings" ]; then
                  SETTINGS="myproject.myprojectsettings.settings"
                  cd myproject
                else
                  echo "Could not find myprojectsettings/ - aborting."
                  ls -la
                  exit 1
                fi

                echo "Using DJANGO_SETTINGS_MODULE=$SETTINGS"
                python manage.py migrate --noinput --settings=$SETTINGS
                python manage.py collectstatic --noinput --settings=$SETTINGS
              '
